"""
MEG Encoder wrapper for Brain MoE-PINN.

MEG (magnetoencephalography) shares temporal resolution with EEG
but measures magnetic fields via SQUID sensors (~306 channels for
Neuromag systems: 102 magnetometers + 204 planar gradiometers).

Design: MEG shares the same BERT-medium backbone (8L x 512d) as EEG,
with a different front-end (CNN for 306 channels vs BIOT for EEG).
This follows the physics: EEG and MEG are generated by the same
primary current sources (Maxwell equations), differing only in
their forward operators (volume conduction vs Biot-Savart).

A shared latent dynamics model with modality-specific front-ends
is the natural architecture (EEG-Datasets.md A.14).

Weight sharing: MEG and EEG use identical BERTBaseEncoder backbones,
so weights can be directly shared or transferred via:
  - shared_encoder: pass the same nn.Module instance (weight tying)
  - load_from_eeg(): copy state dict (cross-modal transfer)
"""

import torch
import torch.nn as nn
from typing import Optional, Dict, List

try:
    from brain_moe_pinn.magi.encoder import BERTBaseEncoder
    BERT_AVAILABLE = True
except ImportError:
    BERT_AVAILABLE = False


class MEGEncoderWrapper(nn.Module):
    """
    MEG encoder sharing the same BERT-medium backbone as EEG.

    Architecture:
        MEG (B, 306, T)
          -> CNN front-end (306 -> 512, MEG-specific learnable filterbank)
          -> BERT-medium (8L x 512d, identical to EEG's backbone)
          -> upscaling projection (512 -> 1024)

    The CNN front-end is MEG-specific (306 channels, no volume conduction).
    The BERT backbone is identical to EEG's Magi BERT-medium and can
    share weights via cross-modal transfer or weight tying.

    Args:
        num_channels: Number of MEG sensors (default 306 for Elekta Neuromag)
        hidden_dim: Transformer dimension (must match EEG encoder, default 512)
        output_dim: Projected output dimension (latent_dim, typically 1024)
        num_layers: Number of Transformer encoder layers (must match EEG, default 8)
        num_heads: Attention heads (default 8 for 512d: 64 per head)
        dropout: Dropout rate
        patch_size_time: Temporal patch size for initial strided conv
        stride_time: Stride for temporal patches
        shared_encoder: Optional shared BERTBaseEncoder (for weight tying with EEG)
    """

    def __init__(
        self,
        num_channels: int = 306,
        hidden_dim: int = 512,
        output_dim: int = 1024,
        num_layers: int = 8,
        num_heads: int = 8,
        dropout: float = 0.1,
        patch_size_time: int = 256,
        stride_time: int = 128,
        shared_encoder: Optional[nn.Module] = None,
    ):
        super().__init__()
        self.num_channels = num_channels
        self.hidden_dim = hidden_dim
        self.output_dim = output_dim
        self.num_layers = num_layers
        self.patch_size_time = patch_size_time
        self.stride_time = stride_time

        # MEG-specific CNN front-end (306 channels -> hidden_dim)
        # Unlike EEG's BIOT embedding, MEG uses a learnable filterbank
        # because MEG channels have no volume conduction distortion
        self.temporal_conv = nn.Sequential(
            nn.Conv1d(num_channels, hidden_dim // 2, kernel_size=7, padding=3, bias=False),
            nn.GELU(),
            nn.Conv1d(hidden_dim // 2, hidden_dim, kernel_size=3, padding=1, bias=False),
            nn.GELU(),
        )

        # Learned positional encoding (max 8192 time steps)
        self.pos_encoding = nn.Parameter(torch.randn(1, 8192, hidden_dim) * 0.02)

        # Transformer backbone: shared with EEG or independent
        # Uses same BERTBaseEncoder as EEG for weight compatibility
        if shared_encoder is not None:
            self.encoder = shared_encoder
            self._shared_backbone = True
        elif BERT_AVAILABLE:
            self.encoder = BERTBaseEncoder(
                hidden_dim=hidden_dim,
                num_layers=num_layers,
                num_heads=num_heads,
                intermediate_size=hidden_dim * 4,
                dropout=dropout,
            )
            self._shared_backbone = False
        else:
            # Fallback to standard nn.TransformerEncoder if Magi not available
            encoder_layer = nn.TransformerEncoderLayer(
                d_model=hidden_dim,
                nhead=num_heads,
                dim_feedforward=hidden_dim * 4,
                dropout=dropout,
                batch_first=True,
                norm_first=True,
            )
            self.encoder = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)
            self._shared_backbone = False

        # Upscaling projection (same architecture as EEG's upscaling_proj)
        self.upscaling_proj = nn.Sequential(
            nn.Linear(hidden_dim, output_dim),
            nn.GELU(),
            nn.LayerNorm(output_dim),
        )

        self._init_weights()

    def _init_weights(self):
        if self._shared_backbone:
            return
        for m in self.modules():
            if isinstance(m, nn.Linear):
                nn.init.xavier_uniform_(m.weight)
            elif isinstance(m, nn.Conv1d):
                nn.init.kaiming_normal_(m.weight, mode="fan_out", nonlinearity="relu")

    def _run_encoder(self, x: torch.Tensor) -> torch.Tensor:
        """Run through the backbone, handling both BERTBaseEncoder and nn.TransformerEncoder."""
        if hasattr(self.encoder, 'bert'):
            # BERTBaseEncoder: has .bert attribute with .transformer
            # Need to run through the transformer layers directly
            h = self.encoder.bert.transformer(x)
            h = self.encoder.bert.layer_norm(h)
            return h
        elif isinstance(self.encoder, nn.TransformerEncoder):
            return self.encoder(x)
        else:
            # Shared encoder that has a forward method
            return self.encoder(x)

    def forward(
        self,
        meg: torch.Tensor,
        return_embeddings: bool = True,
    ) -> Dict[str, torch.Tensor]:
        """
        Args:
            meg: (B, C, T) raw MEG signals
            return_embeddings: If True, return projected embeddings
        Returns:
            dict with:
                - 'last_hidden': (B, T', hidden_dim) encoder output
                - 'embeddings': (B, T', output_dim) projected tokens
        """
        B, C, T = meg.shape
        x = self.temporal_conv(meg)  # (B, hidden_dim, T)
        x = x.transpose(1, 2)  # (B, T, hidden_dim)

        if x.shape[1] <= self.pos_encoding.shape[1]:
            x = x + self.pos_encoding[:, : x.shape[1], :]

        x = self._run_encoder(x)  # (B, T, hidden_dim)

        out = {"last_hidden": x}
        if return_embeddings:
            out["embeddings"] = self.upscaling_proj(x)
        return out

    def set_freeze(self, freeze: bool):
        for param in self.parameters():
            param.requires_grad = not freeze

    def load_from_eeg(self, eeg_encoder_state: Dict[str, torch.Tensor], strict: bool = False):
        """
        Load shared Transformer backbone weights from a pretrained EEG encoder.

        This enables cross-modal transfer: the EEG-trained BERT backbone
        already understands temporal neural dynamics; MEG only needs to
        learn its new front-end (CNN) and fine-tune.

        Args:
            eeg_encoder_state: State dict from EEGEncoderWrapper.encoder.base_encoder
            strict: If True, require exact key match
        """
        if self._shared_backbone:
            print("[MEGEncoderWrapper] Skipping load_from_eeg: backbone is shared (already tied)")
            return

        own_state = self.encoder.state_dict()
        loaded = 0
        skipped = 0
        for k, v in eeg_encoder_state.items():
            if k in own_state and own_state[k].shape == v.shape:
                own_state[k] = v
                loaded += 1
            else:
                skipped += 1

        self.encoder.load_state_dict(own_state, strict=False)
        print(f"[MEGEncoderWrapper] Cross-modal transfer: loaded {loaded} params, skipped {skipped} from EEG encoder")


class MEGProjection(nn.Module):
    """
    Lightweight adapter from MEG hidden_dim to VelocityBrain dim.

    Only used when MEG encoder returns last_hidden (not embeddings).
    When MEGEncoderWrapper returns embeddings, this is not needed.
    """

    def __init__(
        self,
        input_dim: int = 512,
        output_dim: int = 1024,
        dropout: float = 0.1,
    ):
        super().__init__()
        self.projection = nn.Sequential(
            nn.Linear(input_dim, output_dim),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.LayerNorm(output_dim),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.projection(x)


if __name__ == "__main__":
    print("Testing MEGEncoderWrapper (8L x 512d BERT-medium, shared with EEG)...")
    model = MEGEncoderWrapper(num_channels=306, hidden_dim=512, output_dim=1024, num_layers=8, num_heads=8)
    dummy_meg = torch.randn(2, 306, 2560)
    out = model(dummy_meg)
    print(f"  last_hidden shape: {out['last_hidden'].shape}")
    print(f"  embeddings shape: {out['embeddings'].shape}")

    total = sum(p.numel() for p in model.parameters())
    print(f"  total params: {total:,}")
    print("All tests passed!")
