"""Controlled-response and temporal-asymmetry diagnostics.

These helpers produce testable contrasts.  They do not turn observational
prediction into causal identification: causal interpretation still requires
valid interventions, controls, timing, and leakage-free evaluation.
"""

from typing import Callable, Dict, Optional

import torch
from torch import Tensor


def rollout_controlled(
    step_fn: Callable[[Tensor, Tensor], Tensor],
    initial_state: Tensor,
    controls: Tensor,
) -> Tensor:
    """Roll out a state transition under an explicit control sequence.

    ``controls`` has shape ``(T, B, U)`` and the returned trajectory has shape
    ``(T+1, B, D)``.  ``step_fn`` may return the next state directly or a dict
    containing ``next_state``/``z_next``/``delta_z``.
    """
    if initial_state.dim() != 2 or controls.dim() != 3:
        raise ValueError("initial_state must be (B,D), controls must be (T,B,U)")
    if controls.shape[1] != initial_state.shape[0]:
        raise ValueError("controls batch dimension must match initial_state")
    states = [initial_state]
    state = initial_state
    for control in controls:
        prediction = step_fn(state, control)
        state = _extract_next_state(prediction, state)
        if state.shape != initial_state.shape:
            raise ValueError("step_fn returned a state with the wrong shape")
        states.append(state)
    return torch.stack(states, dim=0)


def _extract_next_state(prediction, current: Tensor) -> Tensor:
    if isinstance(prediction, dict):
        if "next_state" in prediction:
            return prediction["next_state"]
        if "z_next" in prediction:
            return prediction["z_next"]
        if "delta_z" in prediction:
            return current + prediction["delta_z"]
        raise ValueError("step_fn dict must contain next_state, z_next, or delta_z")
    return prediction


def intervention_response_metrics(
    treated: Tensor,
    baseline: Tensor,
    dt: float = 1.0,
    intervention_start: int = 0,
) -> Dict[str, Tensor | float]:
    """Compute a controlled trajectory contrast without causal overclaiming.

    Both trajectories use shape ``(T, B, D)`` or ``(T, D)``.  The returned
    effect is ``treated - baseline``.  The metrics quantify magnitude and
    persistence; they do not identify a causal effect unless the contrast is
    generated by a valid intervention design.
    """
    if dt <= 0:
        raise ValueError("dt must be positive")
    if treated.shape != baseline.shape or treated.dim() not in (2, 3):
        raise ValueError("treated and baseline must have matching (T,D) or (T,B,D) shapes")
    if not 0 <= intervention_start < treated.shape[0]:
        raise ValueError("intervention_start must index the trajectory")
    effect = treated - baseline
    if effect.dim() == 2:
        norm = effect.norm(dim=-1)
    else:
        norm = effect.norm(dim=-1).mean(dim=-1)
    post = norm[intervention_start:]
    return {
        "effect_trajectory": effect,
        "effect_norm": norm,
        "peak_effect": post.max(),
        "final_effect": post[-1],
        "cumulative_effect": post.sum() * dt,
        "dt": float(dt),
        "intervention_start": int(intervention_start),
    }


def forward_reverse_prediction_gap(
    trajectory: Tensor,
    one_step_predictor: Callable[[Tensor], Tensor | Dict[str, Tensor]],
) -> Dict[str, Tensor | float]:
    """Measure forward/reverse one-step prediction asymmetry.

    The same predictor is evaluated on the original and time-reversed
    trajectory.  This is an operational arrow-of-time diagnostic, not proof
    of thermodynamic irreversibility.  A caller with odd variables should
    supply a parity-adjusted reversal before invoking this helper.
    """
    if trajectory.dim() != 3 or trajectory.shape[0] < 3:
        raise ValueError("trajectory must have shape (T,B,D) with T >= 3")

    def mse_on(path: Tensor) -> Tensor:
        current = path[:-1]
        target = path[1:]
        prediction = one_step_predictor(current)
        prediction = _extract_next_state(prediction, current)
        if prediction.shape != target.shape:
            raise ValueError("one_step_predictor returned the wrong shape")
        return (prediction - target).square().mean()

    forward_error = mse_on(trajectory)
    reverse_error = mse_on(trajectory.flip(0))
    return {
        "forward_mse": forward_error.detach(),
        "reverse_mse": reverse_error.detach(),
        "forward_reverse_gap": (reverse_error - forward_error).detach(),
        "asymmetry_ratio": (reverse_error / forward_error.clamp_min(1e-12)).detach(),
    }
